### PR TITLE
Consider using a maven project layout

### PR DESCRIPTION
**Pull request by keyboardsamurai**
Using a maven layout, then uploading it to central, would enable many users to make use of this api.

### CODE REVIEW

**Comment by ddossot** [comment]
Agreed, this is a great project... worth making it readily usable.

**Comment by Danw33** [comment]
+1 for this.

@keyboardsamurai It's been over a year since you opened this, have you considered uploading your own fork to central as it seems nothing is going to happen here and that would be really useful :+1:

**Comment by IOAyman** [comment]
+1 @Danw33

I agree with you :+1:

**Comment by dialex** [comment]
OMG, I'm so sorry @keyboardsamurai, I never received a notification about this pull request (my bad!).

I'm cool with adding files and editing the gitignore. However I noticed that, for some reason, Github shows that all other Java files were edited. Was that required or am I missing something?

I never used Maven, so this is pretty new to me. I surely want to recognize your work, by merging it. There's no point in fragmenting the project in forks just because I didn't press the "merge request" button :laughing:

I just want to make sure I can press the button without break anything. One last question, do I have to rebuild the jar files? And javadoc?

Sorry! :disappointed_relieved:

**Comment by keyboardsamurai** [comment]
Hi there, I am glad you are fine with using the proper distribution channels. Unfortunately maven has it's own directory structure which makes moving files around necessary. This in turn deleted the former directory structure and added all files as new. Losing the git history is a bit unfortunate, I agree. If you are really keen on keeping it, I could have another go at it.

**Comment by dialex** [comment]
I don't mind losing the git history. My question is, since the folder structure changes when people refer to javadoc, will namespaces be outdated? Maybe packages will change name?

I think I'll trust you, and risk it. If something breakes and someone creates an issue, I'll review the whole thing. Right now I don't have that time.

**Comment by keyboardsamurai** [comment]
I did not really touch the package names. But I think this is something that should be done prior to submitting it to maven central. The package "print" seems rather global for a repository as big as ours.

**Comment by xafero** [comment]
Sorry, there was no activity, so I converted all packages etc. ... You can use my pull request per jitpack if you'd like or publish it to Maven central.

**Comment by dialex** [comment]
Good news @keyboardsamurai @ddossot @Danw33 @IOAyman !

I just finished merging @xafero contribution. Now the project should be fully compatible with Maven. I'll start testing it right away.

It only took me one year to do it. Sorry 😅

**Comment by dialex** [comment]
Merged here https://github.com/dialex/JCDP/pull/4

**Comment by IOAyman** [comment]
@dialex  Better late than never :smiley: Thanks!

**Pull request closed without merging**
