### PR TITLE
File printer

### PR DESCRIPTION
**Pull request by toyg**
I added a FilePrinter implementation. It lacks tests but it seems to work.

This is instrumental to the [slf4j-jcdp bridge](https://github.com/toyg/slf4j-jcdp) I'm working on, so that one could log to slf4j and have both colorized output in terminal and a traditional log file.

### CODE REVIEW

**Comment by dialex** [comment]
Thanks for expanding JCDP with your PR ;) 

The feature makes sense and fits the scope of the repo, so consider it "pre-approved".
I'll have to code unit tests to check your code though. This might take a while.

I'll keep you posted!

**Comment by dialex** [comment]
We have a problem. This library is compatible with Java 6, yet...

- Your threads code (eg. `AutoCloseable`) requires Java 7.
- Your cross platform line separator (eg. `System.lineSeparator`) requires Java 7.
- Your hashmap insertion method (eg. `lockRegistry.putIfAbsent`)requires Java 8.

Which means, if I accept your code as is, I'll have to increase the minimum required Java version, thus breaking compatibility with anyone currently using Java 6 or 7.

@toyg Why do we need that threading code?

----

> Meanwhile I tried to find some data to support my upgrade decision. It seems Java 6 has been deprecated a long time ago, and Java 8 is the oldest LTS (begin 11 the latest LTS version). Java 8 is also the [most used version](https://www.baeldung.com/java-in-2018) compared to 7 and 6.
 
It seems to me the risk of upgrading is low ✅

**Comment by toyg** [comment]
To be honest, I didn't check what version JCDP was supposed to support - these days I typically write 8+ and in some special cases make an effort for 7. I think the tweaks to go to 7 are easy enough, if you want to settle there; but as I said, 8 is a very safe default in 2019. 

The threading code is for situations where you might have multiple threads trying to log to the same file. It's the sort of thing I would typically address either with a static synchronized queue, or with a lock. This time the lock looked the more straightforward solution.

**Comment by dialex** [comment]
@toyg I finished writing the unit tests. Some pass (the ones that create and config the printer) and [most fail](https://github.com/dialex/JCDP/pull/17/commits/763f0b085d587e4611ee508f53eff4286e9085be) (the ones related with actual printing). So now it's a good opportunity for you to do TDD 😜To run tests, either use your IDE or run `mvn test` on your console.

I did some debugging and found out that when the assertions run, the log file is empty. However when the tests finish running, the same log file is no longer empty. So it seems to me the issue is the "write to file" timing.

**Currently, the log file only gets written once the application finished running.** Was this intentional? Was that to minimize disk writes? I understand that concern, but I think it greatly reduces the usefulness of the log file.

**Comment by toyg** [comment]
Uh no, this shouldn't happen. I'll have a look tomorrow.

**Review by dialex — CHANGES_REQUESTED** [review]
1. Currently, the log file only gets written once the application finished running. Was this intentional? Was that to minimize disk writes? I understand that concern, but I think it greatly reduces the usefulness of the log file.
2. The branch needs to be rebased, and conflicts resolved.
3. All unit tests must pass.

**Comment by dialex** [comment]
This PR has been inactive for too long, so I'll close it for now 😉

**Pull request closed without merging**
