### PR TITLE
Add OSGi support

### PR DESCRIPTION
**Pull request by robertcsakany**
Add exports and bundle menifest headers to deploy in OSGi environment.

### CODE REVIEW

**Comment by dialex** [comment]
Thanks Robert, I'll try to have a look at it this weekend ;) Since it's just config, it should be quick

N00b question: Can you briefly explain me the benefit of this change?

**Comment by robertcsakany** [comment]
This is extending MANIFEST.MF file which containes mandatory tags which is used by OSGi containers. The OSGi bundle is a jar file where MANIFEST.MF defines capabilities / provides. The OSGi containers can deplooy JAr files only with these extended attributes. (See more: https://en.wikipedia.org/wiki/OSGi https://felix.apache.org/documentation/index.html https://karaf.apache.org/ )

**Comment by dialex** [comment]
I can give it a try, but right now I'm on vacation. Not sure I can merge this before the end of the month.

**Comment by dialex** [comment]
Sorry it took so long. I just finished releasing this as v5.3.1
Thank you!

**Pull request closed without merging**
